name: admintools
version: 'v1'
main: org.darbz.admintools.Admintools
api-version: '1.21'
commands:
  Freeze:
    permission: op
  Vanish:
    Permission: op
  Broadcast:
    permission: op
  ItemCreate:
    permission: op
  Heal:
    permission: op
  Pvp:
    permission: op
  effect_checker:
    permission: op
  tempban:
    permission: op
  fly:
    permission: op


